sudo: false
language: cpp
os:
  - linux
  - osx
env:
  global:
    - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
  matrix:
    - TRAVIS_NODE_VERSION="6"
    - TRAVIS_NODE_VERSION="7"
    - TRAVIS_NODE_VERSION="8"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - libstdc++6

before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g node-gyp
  - eval "${MATRIX_EVAL}"
install:
  - npm install
script:
  - npm test

